### ISSUE TITLE
QA6 report

### ISSUE THREAD

**Issue by vv-monsalve** [vv-monsalve/CourierPrime#1]
"Font is monospaced but 2 glyphs have a different width" 
The warn persist but the glyph has the same width. Nevertheless, it's a "nonspacing" subcategory and it turns to width zero after export (which is expected). 
How can this be solved?

## Fontbakery report

Fontbakery version: 0.7.14
<details>
<summary><b>[6] CourierPrime-Regular.ttf</b></summary>
<summary>⚠ <b>WARN:</b> Checking OS/2 achVendID.</summary>
<summary>⚠ <b>WARN:</b> Stricter unitsPerEm criteria for Google Fonts. </summary>
<summary>⚠ <b>WARN:</b> Check if each glyph has the recommended amount of contours.</summary>
<summary>⚠ <b>WARN:</b> Does GPOS table have kerning information?</summary>
<br>

<details>
<summary>⚠ <b>WARN:</b> Checking correctness of monospaced metadata.</summary>

* [com.google.fonts/check/monospace](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/name.html#com.google.fonts/check/monospace)
* ⚠ **WARN** Font is monospaced but 2 glyphs (0.48192771084337355%) have a different width. You should check the widths of: ['uni0326', 'uni0326.case'] [code: mono-outliers]

</details>
<details>
<summary>⚠ <b>WARN:</b> Monospace font has hhea.advanceWidthMax equal to each glyph's advanceWidth?</summary>

* [com.google.fonts/check/monospace_max_advancewidth](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/hhea.html#com.google.fonts/check/monospace_max_advancewidth)
* ⚠ **WARN** This seems to be a monospaced font, so advanceWidth value should be the same across all glyphs, but 0.48% of them have a different value: uni0326 and uni0326.case [code: should-be-monospaced]
* ⚠ **WARN** Double-width and/or zero-width glyphs were detected. These glyphs should be set to the same width as all others and then add GPOS single pos lookups that zeros/doubles the widths as needed: uni0326 and uni0326.case [code: variable-monospaced]

</details>

### Summary

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | ℹ INFO | 🍞 PASS | 🔎 DEBUG |
|:-----:|:----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 0 | 24 | 242 | 25 | 266 | 0 |
| 0% | 0% | 4% | 43% | 4% | 48% | 0% |

**Note:** The following loglevels were omitted in this report:
* **SKIP**
* **INFO**
* **PASS**
* **DEBUG**

**Comment by m4rc1e** [comment]
It's fine. We can ignore it.

**Comment by vv-monsalve** [comment]
Good, thanks
